<a href="https://colab.research.google.com/github/Ankit23232/Python/blob/main/Workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Initialize an empty array with size 2*2
import numpy as np
zero_arr = np.zeros((2,2))
print(zero_arr)

[[0. 0.]
 [0. 0.]]


In [2]:
#Initialize an all one array with size 4*2
import numpy as np
one_arr =np.ones((4,2))
print(one_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#Return a new array of given shape and type, filled with full_value.
import numpy as np
array = np.full((4,2), fill_value = 1000)
print(array)

[[1000 1000]
 [1000 1000]
 [1000 1000]
 [1000 1000]]


In [4]:
#Return a new array of zeros with same shae and type and type a given array.
import numpy as np
array = np.zeros((4,2))
print(array)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
#Return a new array of ones with same shae and type and type a given array.
import numpy as np
array = np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.
import numpy as np
new_list = [1,2,3,4]
array = np.array(new_list)
print(type(array))

<class 'numpy.ndarray'>


In [7]:
#Create an array with values ranging from 10 to 49.
import numpy as np
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
#Create a 3X3 matrix with values ranging
#from 0 to 8.
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Create a 3X3 identity matrix.
import numpy as np
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Create a random array of size 30 and find
#the mean of the array.
import numpy as np
x = np.random.random(30).mean()
print(x)

0.4410596891166258


In [11]:
#Create a 10X10 array with random values and
# find the minimum and maximum values.
import numpy as np
x = np.random.randint(50,size = (10,10))
print("original array = ",x)
xmin, xmax = x.min(), x.max()
print(np.min(x))
print(np.max(x))


original array =  [[35 21 35 13 46 15 16 15 46 33]
 [11  8  9 48 16 40 49 41 12 47]
 [ 7 35 44 37 23 21 38 36 44 16]
 [ 0 43 20 41  9 10 30 34 49 16]
 [22 29  0 11 40 42 34 30  4 22]
 [14 40  9 10 28 10  2  0 23 18]
 [13 27 34 16 33 46 23 30  4 19]
 [ 8 27 10 24  1 37 38 30 43 48]
 [30 27 12 36  5 45 33 22 44 20]
 [ 7  6 21  6  4 16 48 21 26 38]]
0
49


In [12]:
#Create a zero array of size 10 and replace
#5th element with 1.
import numpy as np
x = np.zeros((10))
print(x)
x[5]=1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [13]:
#Reverse an array arr = [1,2,0,0,4,0].
x = [1,2,0,0,4,0]
x.reverse()
print(x)

[0, 4, 0, 0, 2, 1]


In [14]:
#Create a 2d array with 1 on border and 0 inside.
import numpy as np
x = np.ones((5,5))
x [1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
#Add the two array.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = ([9,10])
w = ([11,12])
z = np.add (x,y)
print(z)
x = np.add(v,w)
print(x)

[[ 6  8]
 [10 13]]
[20 22]


In [17]:
#Subtract the two array.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = ([9,10])
w = ([11,12])
z = np.subtract(x,y)
print(z)
x = np.subtract(v,w)
print(x)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [18]:
#Multiply the array with any integers of your choice.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = ([9,10])
w = ([11,12])
z = np.multiply(5,x)
print(z)
a = np.multiply(2,y)
print(a)
x = np.multiply(4,v)
print(x)
a = np.multiply(5,w)
print(a)

[[ 5 10]
 [15 25]]
[[10 12]
 [14 16]]
[36 40]
[55 60]


In [19]:
#Find the square of each element of the array.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = ([9,10])
w = ([11,12])
a = np.square(x)
print(a)
b = np.square(y)
print(b)
c = np.square(v)
print(c)
d = np.square(w)
print(d)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [20]:
#Find the dot product between: v(and)w ; x(and)v ; x(and)y.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = ([9,10])
w = ([11,12])
a = np.dot(v,w)
print(a)
b = np.dot(x,v)
print(b)
c = np.dot(x,y)
print(c)

219
[29 77]
[[19 22]
 [50 58]]


In [21]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = ([9,10])
w = ([11,12])
a = np.concatenate((x,y), axis = 1)
print(a)
b = np.hstack((v,w))
print(b)

[[1 2 5 6]
 [3 5 7 8]]
[ 9 10 11 12]


In [22]:
#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
import numpy as np
x = ([[1,2],[3,5]])
v = ([9,10])
a = np.concatenate(x,v)
print(a)
#Cause we concatenate because size of x = (2,2) and v + (1,2)

TypeError: 'list' object cannot be interpreted as an integer

In [23]:
#Prove A.A−1 = I.
import numpy as np
A = np.array([[3,4],[7,8]])
Aa = (np.linalg.inv(A))
c = (np.dot(A,Aa))
print(c)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [24]:
#Prove AB ̸= BA.
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
c = (np.dot(A,B))
print(c)
d = (np.dot(B,A))
print(d)
print("AB!=BA")

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
AB!=BA


In [25]:
#Prove (AB)' = B'A'
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

C = (np.dot(A,B))
a = (np.linalg.inv(C))
print(a)

Aa = (np.linalg.inv(A))
Bb = (np.linalg.inv(B))
b = (np.dot(Bb,Aa))

print(b)

[[  7.25  -3.25]
 [-12.75   5.75]]
[[  7.25  -3.25]
 [-12.75   5.75]]


In [26]:
import numpy as np
A = ([[2,-3,1],
      [1,-1,2],
      [3,1,-1]])
B = ([1,-3,9])

W = (np.linalg.inv(A))
S = (np.dot(W,B))

print(S)

[ 2.10526316  0.26315789 -2.42105263]


In [27]:
#Element-wise Addition:
import time
import numpy as np

List1 = [i for i in range(1000000)]
List2 = [i for i in range (1000000)]

start_time = time.time()
result  = (List1 + List2 for List1.List2 in zip (List1,List2))
list_time = time.time() - start_time
print (f"Using python list : {list_time:.6f} sec ")

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result = array1 + array2
array_time = time.time() - start_time
print (f" using numpy array : {array_time:.6f} sec")

Using python list : 0.000152 sec 
 using numpy array : 0.006423 sec


In [28]:
import time
import numpy as np

List1 = (i for i in range(1000000))
List2 = (i for i in range(1000000))

start_time = time.time()
result = (List1 * List2 for List1,List2 in zip (List1,  List2))
List_time = time.time() - start_time
print(f"Using python list : {List_time:.6} sec")

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result = (array1 * array2 for array1,array2 in zip(array1,array2))
array_time = time.time() - start_time
print(f"Using numpy : {array_time:.6} sec")

Using python list : 8.44002e-05 sec
Using numpy : 0.00016737 sec


In [29]:
import time
import numpy as np

List1 = (i for i in range(1000000))
List2 = (i for i in range(1000000))

start_time = time.time()
dot_product = sum(list1 * list2 for list1, list2 in zip(List1, List2))
List_time = time.time() - start_time
print(f"Using python : {List_time:.6} sec")

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result = np.dot(array1, array2)
array_time = time.time() - start_time
print(f"Using python : {array_time:.6} sec")

Using python : 0.208899 sec
Using python : 0.00169492 sec


In [ ]:
import time
import numpy as np

def list(A, B):
    result = [[sum(a * b for a, b in zip(A_row, B_col)) for B_col in zip(*B)] for A_row in A]
    return result

list1 = [[i + j for j in range(1000)] for i in range(1000)]
list2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
result_list = list(list1, list2)
list_time = time.time() - start_time
print(f"Using python :{list_time:.6f}sec")

array1 = np.arange(1000000).reshape(1000, 1000)
array2 = np.arange(1000000, 2000000).reshape(1000, 1000)

start_time = time.time()
result_array = np.dot(array1, array2)
array_time = time.time() - start_time
print(f"Using numpy : {array_time:.6f} sec")
